accounts/urls.py
from django.urls import path, include
from .views import RegistrationView

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', RegistrationView.as_view(), name='register'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from docs.views import DocumentListView
from products.views import ProductListView, QuestionList
from contents.views import search
from .views import Index

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name='home'),
    path('faq', QuestionList.as_view(), name='faq'),
    path('files/', DocumentListView.as_view(), name='files'),
    path('products/', ProductListView.as_view(), name='products'),
    path('search/', search, name='search'),
    path('accounts/', include('accounts.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save 
from django.dispatch import receiver

class User(AbstractUser):
    email = models.EmailField()

    def logged_in(self):
        return self.last_login


class Profile(models.Model):

    TEAM_CHOICES = [
        ('IB', 'INBOUND'),
        ('OB', 'OUTBOUND'),
        ('WI', 'WALK IN'),
        ('FD', 'FOOD'),
        ('SM', 'SOCIAL MEDIA'),
        ('OT', 'OTHER'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    team = models.CharField(max_length=150, choices=TEAM_CHOICES, default='OT',)
    avatar = models.ImageField(blank=True, null=True, upload_to='avatars/', default='avatars/avatar.png')

    def __str__(self):
        return self.user.username


"""receivers to add a Profile for newly created users"""
@receiver(post_save, sender=User) 
def create_user_profile(sender, instance, created, **kwargs):
     if created:
         Profile.objects.create(user=instance)

@receiver(post_save, sender=User) 
def save_user_profile(sender, instance, **kwargs):
     instance.profile.save()

contents/models.py
from django.db import models
from tinymce import HTMLField

class Category(models.Model):
    title = models.CharField(max_length=120)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Categories'


class Activity(models.Model):
    title = models.CharField(max_length=120)
    description = HTMLField()
    steps = HTMLField(blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Activities'


class TicketType(models.Model):
    title = models.CharField(max_length=120)
    content = HTMLField()

    def __str__(self):
        return self.title

    class Meta:
        pass

docs/models.py
import os
from django.db import models

class Document(models.Model):
    file = models.FileField(upload_to='documents/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.file.name

    def get_filename(self):
        return os.path.basename(self.file.name)

products/models.py
from django.db import models
from tinymce import HTMLField

class ProductType(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Scenario(models.Model):
    name = models.CharField(max_length=200)
    description = HTMLField()
    procedures = HTMLField(blank=True)
    product = models.ForeignKey('ProductType', on_delete=models.CASCADE)

    def __str__(self):
        return self.name



class Notification(models.Model):
    title = models.CharField(max_length=200)
    content = HTMLField()
    resolved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Question(models.Model):
    title = models.CharField(max_length=200)
    answer = HTMLField()
    featured = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Tool(models.Model):
    name = models.CharField(max_length=200)
    link = models.URLField()

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class RegistrationForm(UserCreationForm):

    TEAM_CHOICES = (
        ('IB', 'INBOUND'),
        ('OB', 'OUTBOUND'),
        ('WI', 'WALK IN'),
        ('FD', 'FOOD'),
        ('SM', 'SOCIAL MEDIA'),
        ('OT', 'OTHER')
    )

    team = forms.ChoiceField(choices=TEAM_CHOICES)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('email', 'team',)

accounts/views.py
from django.shortcuts import render,redirect
from django.views.generic import View
from django.contrib import messages
from django.http import HttpResponse

from .forms import RegistrationForm


class RegistrationView(View):
    template_name = 'register.html'
    form_class = RegistrationForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save()
            user.profile.team = form.cleaned_data.get('team')
            user.save()
            return redirect('login')
        else:
            return render(request, self.template_name, {'form': form})

contents/views.py
from django.db.models import Count, Q
from django.shortcuts import render
from django.views.generic import ListView

from products.models import Scenario
from .models import Activity

class ActivityList(ListView):
    model = Activity
    context_object_name = 'activities'
    template_name = 'activity.html'


def search(request):
    queryset = Scenario.objects.all()
    query = request.GET.get('q')
    if query:
        queryset = queryset.filter(
            Q(name__icontains=query) |
            Q(description__icontains=query)
        ).distinct()

    context = {
        'queryset': queryset,
    }
    return render(request, 'search_results.html', context)

docs/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Document


class DocumentListView(ListView):
    model = Document
    template_name = 'files.html'
    context_object_name = 'docs'

products/views.py
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import ProductType, Question

class ProductListView(ListView):
    model = ProductType
    context_object_name = 'products'
    template_name = 'products.html'


@method_decorator(login_required, name='dispatch')
class QuestionList(ListView):
    model = Question
    context_object_name = 'questions'
    template_name = 'faq.html'

src/views.py
from django.views.generic import View
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from products.models import Notification, Question, Tool


@method_decorator(login_required, name='dispatch')
class Index(View):
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        recent_notifications = Notification.objects.all()[1:4]
        featured_qns = Question.objects.filter(featured=True)[:5]
        tools = Tool.objects.all()
        return render(request, self.template_name, {'notifications': recent_notifications, 'questions': featured_qns, 'tools': tools})

templates/activity.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    {% for activity in activities %}
    <div class="row">
        {% if activity.steps  %}
        <div class="col-md-7">
            <h3>{{activity.title}}</h3>
            {{activity.description|safe}}
        </div>
        <div class="col-md-5">
            <details>Steps</details>
            <summary>
                {{activity.steps|safe}}
            </summary>
        </div>
        {% else %}
        <div class="col-md-12">
            <h3>{{activity.title}}</h3>
            {{activity.description|safe}}
        </div>
        {% endif %}


    </div>
    {% endfor %}

</div>

{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Asap:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet"> 



    <title>SB - Intranet</title>
  </head>
  <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container">
                  <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="{% static 'img/logo.png' %}" alt="SafeBoda" />
                  </a>
                  <button
                    class="navbar-toggler"
                    type="button"
                    data-toggle="collapse"
                    data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                  >
                    <span class="navbar-toggler-icon"></span>
                  </button>
              
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                      {% if request.user.is_authenticated %}
                      <li class="nav-item active">
                        <a class="nav-link" href="{% url 'home' %}"
                          >Home <span class="sr-only">(current)</span></a
                        >
                      </li>
                      
                      <li class="nav-item active">
                          <a class="nav-link" href="{% url 'files' %}"
                            >Files</a
                          >
                        </li>
                      <li class="nav-item active">
                          <a class="nav-link" href="{% url 'products' %}"
                            >Products</a
                          >
                        </li>
                        <li class="nav-item active">
                          <a class="nav-link" href="{% url 'faq' %}"
                            >FAQs</a
                          >
                        </li>
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                         {{request.user.username}}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Profile</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        </div>
                    </li>
                    <button data-toggle="modal" data-target="#exampleModal" class="btn btn-outline-primary my-1 my-sm-0" type="button">Ask</button>
                      {% else %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">LOGIN</a>
                        </li>
                      {% endif %}

                    </ul>
                    
                    
                  </div>
                </div>
              </nav>

          {% if request.user.is_authenticated %}
       <div class="container mt-2">
          <div class="alert alert-{% if notification.resolved %}success{% else %}danger{% endif%}" role="alert">
            <h4 class="alert-heading">{{notification.title}}</h4>
            <p>{{notification.content|safe}}</p>
            <hr>
            <p class="mb-0">Whenever you need to, be sure to use margin utilities to keep things nice and tidy.</p>
          </div>
        
       </div>

       {% endif %}
    {% block content %}
    {% endblock content %}

    <!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
      Launch demo modal
    </button> -->

    <!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ask A Question</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
            <form>
                <div class="form-group">
                    <label for="inputEmail4">Email</label>
                    <input type="email" class="form-control" id="inputEmail4">
                </div>
                <div class="form-group">
                  <label for="inputAddress">Name</label>
                  <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
                </div>
                <div class="form-group">
                  <label for="inputAddress2">Subject</label>
                  <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
                </div>
                
                <div class="form-group">
                    <label for="exampleFormControlTextarea1">Question</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="6"></textarea>
                  </div>
                <button type="submit" class="btn btn-primary">Send</button>
              </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>

    <footer class="bg-light">
      <div class="card p-3 mt-3 text-center">
        <p>&copy; <a href="https://safeboda.com/ug/">SafeBoda</a></p>
      </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/faq.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
                <h3>Frequently Asked Questions (FAQs).</h3>
            {% for question in questions %}
            <details class="card p-3 shadow">
                <summary class="mt-2">{{question.title}}</summary>
                <p>{{question.answer|safe}}</p>
            </details>
            {% endfor %}

            <!-- <details class="card p-3">
                <summary class="mt-2">Question 2</summary>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut, impedit. Blanditiis iure dignissimos, earum incidunt quisquam neque? Obcaecati delectus aperiam assumenda voluptatibus? Error repellendus explicabo aperiam vel vero quo ad.</p>
            </details> -->
            
        </div>
    </div>
</div>

{% endblock content %}

templates/files.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<header class="jumbotron">
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <h1>SafeBoda Support</h1>
          </div>
        </div>
      </header>


<div class="container">
        <div class="row">
            <div class="col-md-7">
                    <nav>
                            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                              <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Starter</a>
                              
                            </div>
                          </nav>
                          <div class="tab-content" id="nav-tabContent">
                            <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                                    <div class="embed-responsive embed-responsive-16by9">
                                            <iframe class="embed-responsive-item" src="https://drive.google.com/embeddedfolderview?id=1WbO0J9ezL7_r-PuXjFSuA0eHKrPDYiGJ#list" allowfullscreen></iframe>
                                          </div>
                              </div>
                            
                          </div>
            </div>
            <div class="col-md-5">

              <h5>OTHER FILES</h5>
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">File</th>
                    <th scope="col">Last Updated</th>
                  </tr>
                </thead>
                <tbody>
                  {% for doc in docs %}
                  <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td><a href="{{doc.file.url}}">{{doc.get_filename}}</a> </td>
                    <td>{{doc.updated_at|date}}</td>
                  </tr>
                  {% endfor %}

                </tbody>
              </table>
            </div>
        </div>
    </div>

    <hr class="container">

{% endblock content %}

templates/index.html
{% extends 'base.html' %} {% block content %} {% load static %}



<header>
  <div class="container">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'img/SafeBoda-1.jpg' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="{% static 'img/SafeBoda-1.jpg' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="{% static 'img/SafeBoda-1.jpg' %}" class="d-block w-100" alt="...">
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</header>

<main>

    <div class="container mt-4">
      <div class="row">
        <div class="col-md-8">
            <div class="card shadow">
              <div class="card-body">
                <h5 class="card-title">
                  CUSTOMER HANDLING
                </h5>

                <h6><b>The Five Pillars of Great Customer Care.</b></h6>
                <p>
                  <b>PASSION</b> - What does this look like? Do a demo and practice in meeting 
Customers need to know that you are fighting for them and that their satisfaction is important to you. This can be seen/heard in the tone of voice, energy, and attentiveness to listen.
                </p>

                <p>
                  <b>EMPATHY</b> - What does this look like? Do a demo and practice in meeting
Empathy is the ability to understand and share the feelings of another. Customers need to realize that you truly understand what they want and know that you have put yourself in their shoes.
                </p>


                <p>
                  <b>COMMUNICATION</b> - What does this look like? Do a demo and practice in meeting
As a call center, Communication is our priority. Always communicate with the customers about what is being done and never leave a customer hanging wondering what has been done or what is being done to help them.
                </p>

                <p>
                  <b>ACTION</b> - What does this look like? Do a demo and practice in meeting
 If a customer feels like we don’t care about certain problems, they won’t bother using the system again (ordering again, Sending or any other). You need to explain to them what we are going to fix the problem, so they know we take the business seriously and are not just trying to shut them up. Give them the time frames and make sure the issue is resolved. It's always good to under promise and over deliver than vice versa.
                </p>

                  
                  

                </div>
              </div>
        </div>
        <div class="col-md-4">
        <div class="row">
        <div class="col-md-12">
          <h5 class="card-title">Recent Notifications</h5>
          {% for notification in notifications %}
          <div class="alert alert-{% if notification.resolved %}success{% else %}danger{% endif%}" role="alert">
            {{notification.title}}
          </div>
          {% endfor %}

        </div>

        <div class="col-md-12">
            <h5 class="card-title">
                FAQs
              </h5>
              {% for question in questions %}
              <details class="card p-3">
                  <summary class="mt-2">{{question.title}}</summary>
                  <p>{{question.answer|safe}}</p>
              </details>
              {% endfor %}
        </div>
      </div>
        </div>
      </div>
    </div>

    <hr class="container">

    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <div class="card shadow">

            <div class="card-body">
              <h5 class="card-title">
                Tools
              </h5>
  
              <ul>
                {% for tool in tools %}
                <li><a href="{{tool.link}}">{{tool.name|upper}}</a></li>
                {% endfor %}

                
              </ul>
    
            </div>
          </div>
        </div>
        
      </div>
    </div>

    <hr class="container">




</main>

{% endblock content %}

templates/products.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    
    <div class="row">
        <div class="col-md-12">
            <form action="{% url 'search' %}">
                <div class="input-group mb-3">
                    <input type="search" name="q" class="form-control"  aria-describedby="helpText">
                    
                    <div class="input-group-append">
                        <span class="input-group-text">SEARCH</span>
                    </div>
                    
                </div>
            </form>
        </div>
        <div class="col-md-12 mt-4">
            {% for product in products %}
            <details class="card p-3 shadow">
                <summary class="mt-2">{{product.name}}</summary>
                {% for activity in product.scenario_set.all %}
                <details class="card p-2 mt-2 shadow">
                    <summary class="mt-2" ><a href="#{{activity.name}}">{{activity.name}}</a></summary>
                    <p>{{activity.description|safe}}</p>
                </details>
                
                {% endfor %}

            </details>
            {% endfor %}
        </div>


    </div>
    

</div>

{% endblock content %}

templates/register.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Sign up</h3>
          <form method="post" action="{% url 'register' %}">
            {% csrf_token %}
            {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
  {% endif %}

  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}

      {% if form.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}
            <button type="submit" class="btn btn-primary btn-block">Create an account</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          Already have an account? <a href="{% url 'login' %}">Log in</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/search_results.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h5>Search results</h5>
            <hr>
            {% for activity in queryset %}
            {{activity.product.name}} > 
            <a href="{% url 'products' %}">{{ activity.name }}</a>
            <hr>

            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}